<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecorext" nsURI="http://ecorext/1.0" nsPrefix="ecorext">
  <eClassifiers xsi:type="ecore:EClass" name="Ecorext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="newPackages" ordered="false"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classesExtensions" ordered="false"
        upperBound="-1" eType="#//ClassExtension" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" ordered="false"
        upperBound="-1" eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassExtension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedExistingClass"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newProperties" ordered="false"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledRules" ordered="false"
        upperBound="-1" eType="#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepRule" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overridenBy" ordered="false"
        upperBound="-1" eType="#//Rule" eOpposite="#//Rule/overrides"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="overrides" eType="#//Rule"
        eOpposite="#//Rule/overridenBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="main" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
