<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="javaxdsml" nsURI="http://www.gemoc.org/sequential_xdsml" nsPrefix="javaxdsml">
  <eClassifiers xsi:type="ecore:EClass" name="SequentialLanguageDefinition" eSuperTypes="../../org.gemoc.xdsmlframework.xdsml.model/model/xdsml_base.ecore#//LanguageDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dsaProject" eType="#//DSAProject"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DSAProject" eSuperTypes="../../org.gemoc.xdsmlframework.xdsml.model/model/xdsml_base.ecore#//ProjectResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeExecutorClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="URI of the class that implement the code excutor required by the engine.&#xD;&#xA;If null or empty, a default K3 code executor will be generated and used."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entryPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
