language: java

## http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/
sudo: required
dist: trusty
env:
  global:
    - MAVEN_OPTS="-Xmx2g"
jdk:
  - oraclejdk8
before_install: echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P use_CI_repositories,modelanimation,trace_and_framework,java_execution
script:
# Build update-site
- mvn -P use_CI_repositories,modelanimation,trace_and_framework,java_execution clean verify
# Rename the zipped update site to nightly
- mv simulationmodelanimation/releng/fr.obeo.dsl.debug.repository/target/fr.obeo.dsl.debug.repository-*-SNAPSHOT.zip
  simulationmodelanimation/releng/fr.obeo.dsl.debug.repository/target/fr.obeo.dsl.debug.repository-nightly.zip
# Prepare local dirs to deploy: copy repository
- chmod a+x prepare-deploy-local-dir.sh
- ./prepare-deploy-local-dir.sh $TRAVIS_BUILD_DIR/simulationmodelanimation/nightly
deploy:
  provider: s3
  access_key_id: AKIAJJVZATSVUD3VGHXA
  secret_access_key:
    secure: HBO4fqSg6EICEfwjo4Kzmu9b8+oMATdaPMadSrGSDK8jcKMcJfZBaqITdbce7hEHZHqNX8ztmfil93ybkzWOsXwMCH6sALtPQp+yl6MjcqXlCIHsecA3wT05nvJngdvO/vUkXM9k64G3Nne1Ii5HcSWAPWXuuM1IbAr57AcLI50t4Kg2tAjSnbz1huI0S8wLNHEWLhn45Cl3dn9nm5F0WZM4qS9sawWfDxWv2Y05yekvJNm++L3wX0W1fjeT1Qghz5l/cs73zxzrLswIBJxX9H9AnzCgOh4Z+N+rsEDk3B3AtheAivMjo5a/00hvqzFDtZDeRS9KW7jOpUe4HMoIy0XX7D4n98XCfii1/MqjcbkMvK3h45i4uwb6/aCe8w9BAmKkT+gYuSRLgy9QgAF2FvkIs+i9mmbgGXxjA85lrOjOd8iPHpgJYzfJPF2KQe1OT3bi3azYM6+C1UpUWRajaJmjQi+Cu+EYc3pRxh5dXJJmUXQuTaTtRyjupvk7NRciCXuq17YPuX1Zr9HObqF+2XY+e9/s2s+RFux/Sti0GP0TQO/neb1e8MDfGGjPafKzAqV1mOIGJBvnWrS+7+KLeK5AIN7NZcMfD1leggT6wDimvxh/JfPUkEetWl1KasdL2eXhQRwVRU9IkEwFY2s3oLzEqcp8uZtNuKKTjgIWUzw=
  bucket: obeo-siriuslab-nightly
  local-dir: "${TRAVIS_BUILD_DIR}/simulationmodelanimation/nightly"
  upload-dir: "SiriusAnimator/${TRAVIS_BRANCH}"
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  on:
      branch: master





