<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="richgenerictrace" nsURI="richgenerictrace" nsPrefix="richgenerictrace">
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//ExecutionState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedObjects" upperBound="-1"
        eType="#//TracedObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentState" eType="#//ExecutionState"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentStep" eType="#//Step"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="current" eType="#//Value"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedProperty" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executionStates" upperBound="-1"
        eType="#//ExecutionState" eOpposite="#//ExecutionState/values"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextValue" eType="#//Value"
        derived="true" eOpposite="#//Value/previousValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousValue" eType="#//Value"
        derived="true" eOpposite="#//Value/nextValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//Value" eOpposite="#//Value/executionStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endingSteps" upperBound="-1"
        eType="#//Step" eOpposite="#//Step/endingState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextState" eType="#//ExecutionState"
        derived="true" eOpposite="#//ExecutionState/previousState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousState" eType="#//ExecutionState"
        derived="true" eOpposite="#//ExecutionState/nextState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startingSteps" upperBound="-1"
        eType="#//Step" containment="true" eOpposite="#//Step/startingState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextStep" eType="#//Step"
        derived="true" eOpposite="#//Step/previousStep"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousStep" eType="#//Step"
        derived="true" eOpposite="#//Step/nextStep"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endingState" eType="#//ExecutionState"
        eOpposite="#//ExecutionState/endingSteps"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startingState" lowerBound="1"
        eType="#//ExecutionState" eOpposite="#//ExecutionState/startingSteps"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentStep" eType="#//Step"
        derived="true" eOpposite="#//Step/childrenSteps"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliedRule" lowerBound="1"
        eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childrenSteps" eType="#//Step"
        eOpposite="#//Step/parentStep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueSequences" upperBound="-1"
        eType="#//ValueSequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
