<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mmfootprint" nsURI="http://xmof/mmfootprint/1.0" nsPrefix="mmfootprint">
  <eClassifiers xsi:type="ecore:EClass" name="Footprint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metamodelEPackage" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="analyzedObjectURI" lowerBound="1"
        eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eModelElementAccesses"
        upperBound="-1" eType="#//EModelElementAccess" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EModelElementAccess">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eModelElement" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessLocations" upperBound="-1"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationID" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
