<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="base" nsURI="http://base/1.0" nsPrefix="base">
  <eClassifiers xsi:type="ecore:EClass" name="SpecificTrace">
    <eGenericSuperTypes eClassifier="ecore:EClass ../../fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Trace">
      <eTypeArguments eClassifier="ecore:EClass ../../fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SequentialStep">
        <eTypeArguments eClassifier="#//Steps/SpecificStep"/>
      </eTypeArguments>
      <eTypeArguments eClassifier="#//States/SpecificTracedObject">
        <eTypeArguments>
          <eUpperBound eClassifier="#//States/SpecificDimension">
            <eTypeArguments>
              <eUpperBound eClassifier="#//States/SpecificValue"/>
            </eTypeArguments>
          </eUpperBound>
        </eTypeArguments>
      </eTypeArguments>
      <eTypeArguments eClassifier="#//States/SpecificState"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eSubpackages name="Steps" nsURI="http://events/1.0" nsPrefix="events">
    <eClassifiers xsi:type="ecore:EClass" name="SpecificStep" abstract="true" interface="true"
        eSuperTypes="../../fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Step">
      <eStructuralFeatures xsi:type="ecore:EReference" name="startingState" lowerBound="1"
          eType="#//States/SpecificState" eOpposite="#//States/SpecificState/startedSteps"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endingState" eType="#//States/SpecificState"
          eOpposite="#//States/SpecificState/endedSteps"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RootImplicitStep" eSuperTypes="../../fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//SmallStep"/>
  </eSubpackages>
  <eSubpackages name="States" nsURI="http://tracedclasses/1.0" nsPrefix="tracedclasses">
    <eClassifiers xsi:type="ecore:EClass" name="SpecificState" eSuperTypes="../../fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//State">
      <eOperations name="getValuesView" upperBound="-1" eType="ecore:EClass ../../fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Value"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startedSteps" upperBound="-1"
          eType="#//Steps/SpecificStep" eOpposite="#//Steps/SpecificStep/startingState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endedSteps" upperBound="-1"
          eType="#//Steps/SpecificStep" eOpposite="#//Steps/SpecificStep/endingState"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificAttributeValue" abstract="true"
        interface="true" eSuperTypes="#//States/SpecificValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificDimension" abstract="true">
      <eTypeParameters name="ValueSubType">
        <eBounds eClassifier="#//States/SpecificValue"/>
      </eTypeParameters>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Dimension">
        <eTypeArguments eTypeParameter="#//States/SpecificDimension/ValueSubType"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificTracedObject" abstract="true">
      <eTypeParameters name="DimensionSubType"/>
      <eGenericSuperTypes eClassifier="ecore:EClass ../../fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//TracedObject">
        <eTypeArguments eClassifier="#//States/SpecificDimension">
          <eTypeArguments/>
        </eTypeArguments>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificReferenceValue" abstract="true"
        interface="true" eSuperTypes="#//States/SpecificValue">
      <eTypeParameters name="T"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SpecificValue" abstract="true" eSuperTypes="../../fr.inria.diverse.trace.commons.model/model/GenericTrace.ecore#//Value"/>
  </eSubpackages>
</ecore:EPackage>
