<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="trace" nsURI="http://www.gemoc.org/generic_trace" nsPrefix="trace">
  <eClassifiers xsi:type="ecore:EDataType" name="ISerializable" instanceClassName="byte[]"/>
  <eClassifiers xsi:type="ecore:EClass" name="MSEOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mse" lowerBound="1" eType="#//MSE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSE" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//ENamedElement">
    <eOperations name="getCaller" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eOperations name="getAction" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSEModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMSEs" upperBound="-1"
        eType="#//MSE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericMSE" eSuperTypes="#//MSE">
    <eOperations name="getCaller" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return callerReference;"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getAction" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return actionReference;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callerReference" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionReference" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step" abstract="true">
    <eTypeParameters name="StateSubType">
      <eBounds eClassifier="#//State">
        <eTypeArguments/>
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mseoccurrence" eType="#//MSEOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startingState" lowerBound="1"
        volatile="true" transient="true" derived="true">
      <eGenericType eTypeParameter="#//Step/StateSubType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endingState" volatile="true"
        transient="true" derived="true">
      <eGenericType eTypeParameter="#//Step/StateSubType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigStep" abstract="true">
    <eTypeParameters name="StepSubtype">
      <eBounds eClassifier="#//Step">
        <eTypeArguments eTypeParameter="#//BigStep/StateSubType"/>
      </eBounds>
    </eTypeParameters>
    <eTypeParameters name="StateSubType">
      <eBounds eClassifier="#//State">
        <eTypeArguments/>
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//BigStep/StepSubtype"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Step">
      <eTypeArguments eTypeParameter="#//BigStep/StateSubType"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmallStep" abstract="true">
    <eTypeParameters name="StateSubType">
      <eBounds eClassifier="#//State">
        <eTypeArguments/>
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Step">
      <eTypeArguments eTypeParameter="#//SmallStep/StateSubType"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequentialStep">
    <eTypeParameters name="StepSubtype">
      <eBounds eClassifier="#//Step">
        <eTypeArguments eTypeParameter="#//SequentialStep/StateSubType"/>
      </eBounds>
    </eTypeParameters>
    <eTypeParameters name="StateSubType">
      <eBounds eClassifier="#//State">
        <eTypeArguments/>
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//BigStep">
      <eTypeArguments eTypeParameter="#//SequentialStep/StepSubtype"/>
      <eTypeArguments eTypeParameter="#//SequentialStep/StateSubType"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelStep">
    <eTypeParameters name="StepSubtype">
      <eBounds eClassifier="#//Step">
        <eTypeArguments eTypeParameter="#//ParallelStep/StateSubType"/>
      </eBounds>
    </eTypeParameters>
    <eTypeParameters name="StateSubType">
      <eBounds eClassifier="#//State">
        <eTypeArguments eTypeParameter="#//ParallelStep/StepSubtype"/>
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//BigStep">
      <eTypeArguments eTypeParameter="#//ParallelStep/StepSubtype"/>
      <eTypeArguments eTypeParameter="#//ParallelStep/StateSubType"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericSequentialStep">
    <eGenericSuperTypes eClassifier="#//SequentialStep">
      <eTypeArguments eClassifier="#//GenericStep"/>
      <eTypeArguments eClassifier="#//GenericState"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//GenericStep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericParallelStep">
    <eGenericSuperTypes eClassifier="#//ParallelStep">
      <eTypeArguments eClassifier="#//GenericStep"/>
      <eTypeArguments eClassifier="#//GenericState"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//GenericStep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericSmallStep">
    <eGenericSuperTypes eClassifier="#//SmallStep">
      <eTypeArguments eClassifier="#//GenericState"/>
    </eGenericSuperTypes>
    <eGenericSuperTypes eClassifier="#//GenericStep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace" abstract="true">
    <eTypeParameters name="StepSubType">
      <eBounds eClassifier="#//Step">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eTypeParameters name="TracedObjectSubtype">
      <eBounds eClassifier="#//TracedObject">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eTypeParameters name="StateSubType">
      <eBounds eClassifier="#//State">
        <eTypeArguments/>
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootStep" lowerBound="1"
        containment="true">
      <eGenericType eTypeParameter="#//Trace/StepSubType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedObjects" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//Trace/TracedObjectSubtype"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//Trace/StateSubType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="launchconfiguration" lowerBound="1"
        eType="#//LaunchConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedObject" abstract="true">
    <eTypeParameters name="DimensionSubType">
      <eBounds eClassifier="#//Dimension">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimensions" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//TracedObject/DimensionSubType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dimension" abstract="true">
    <eTypeParameters name="ValueSubType">
      <eBounds eClassifier="#//Value">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        containment="true">
      <eGenericType eTypeParameter="#//Dimension/ValueSubType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true">
    <eTypeParameters name="StateSubType">
      <eBounds eClassifier="#//State">
        <eTypeArguments/>
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        volatile="true" transient="true" derived="true">
      <eGenericType eTypeParameter="#//Value/StateSubType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" abstract="true">
    <eTypeParameters name="StepSubType">
      <eBounds eClassifier="#//Step">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eTypeParameters name="ValueSubType">
      <eBounds eClassifier="#//Value">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startedSteps" upperBound="-1"
        volatile="true" transient="true" derived="true">
      <eGenericType eTypeParameter="#//State/StepSubType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endedSteps" upperBound="-1"
        volatile="true" transient="true" derived="true">
      <eGenericType eTypeParameter="#//State/StepSubType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        volatile="true" transient="true" derived="true">
      <eGenericType eTypeParameter="#//State/ValueSubType"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericReferenceValue" eSuperTypes="#//GenericValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceValue" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericDimension">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynamicProperty" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    <eGenericSuperTypes eClassifier="#//Dimension">
      <eTypeArguments eClassifier="#//GenericValue"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericTracedObject">
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//TracedObject">
      <eTypeArguments eClassifier="#//GenericDimension"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericState">
    <eOperations name="getValues" upperBound="-1" eType="#//GenericValue">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getValuesRef();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getStartedSteps" upperBound="-1" eType="#//GenericStep">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getStartedStepsRef();"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getEndedSteps" upperBound="-1" eType="#//GenericStep">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getEndedStepsRef();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valuesRef" upperBound="-1"
        eType="#//GenericValue" eOpposite="#//GenericValue/statesRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startedStepsRef" upperBound="-1"
        eType="#//GenericStep" eOpposite="#//GenericStep/startingStateRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endedStepsRef" upperBound="-1"
        eType="#//GenericStep" eOpposite="#//GenericStep/endingStateRef"/>
    <eGenericSuperTypes eClassifier="#//State">
      <eTypeArguments eClassifier="#//GenericStep"/>
      <eTypeArguments eClassifier="#//GenericValue"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericTrace">
    <eTypeParameters name="StepSubType">
      <eBounds eClassifier="#//GenericStep"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Trace">
      <eTypeArguments eTypeParameter="#//GenericTrace/StepSubType"/>
      <eTypeArguments eClassifier="#//GenericTracedObject">
        <eTypeArguments/>
      </eTypeArguments>
      <eTypeArguments eClassifier="#//GenericState"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericAttributeValue" abstract="true"
      eSuperTypes="#//GenericValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanAttributeValue" eSuperTypes="#//GenericAttributeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerAttributevalue" eSuperTypes="#//GenericAttributeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringAttributeValue" eSuperTypes="#//GenericAttributeValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LaunchConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//LaunchConfigurationParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LaunchConfigurationParameter" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageNameParameter" eSuperTypes="#//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddonExtensionParameter" eSuperTypes="#//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelURIParameter" eSuperTypes="#//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnimatorURIParameter" eSuperTypes="#//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntryPointParameter" eSuperTypes="#//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitializationArgumentsParameter" eSuperTypes="#//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelRootParameter" eSuperTypes="#//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitializationMethodParameter" eSuperTypes="#//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericStep" abstract="true">
    <eOperations name="getStartingState" lowerBound="1" eType="#//GenericState"/>
    <eOperations name="getEndingState" eType="#//GenericState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startingStateRef" lowerBound="1"
        eType="#//GenericState" eOpposite="#//GenericState/startedStepsRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endingStateRef" eType="#//GenericState"
        eOpposite="#//GenericState/endedStepsRef"/>
    <eGenericSuperTypes eClassifier="#//Step">
      <eTypeArguments eClassifier="#//GenericState"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericValue" abstract="true">
    <eOperations name="getStates" lowerBound="1" upperBound="-1" eType="#//GenericState">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="body" value="return getStatesRef();"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statesRef" upperBound="-1"
        eType="#//GenericState" eOpposite="#//GenericState/valuesRef"/>
    <eGenericSuperTypes eClassifier="#//Value">
      <eTypeArguments eClassifier="#//GenericState"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
