<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="trace" nsURI="http://www.gemoc.org/generic_trace" nsPrefix="trace">
  <eClassifiers xsi:type="ecore:EDataType" name="ISerializable" instanceClassName="byte[]"/>
  <eClassifiers xsi:type="ecore:EClass" name="MSEOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mse" lowerBound="1" eType="//MSE"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameters" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSE" abstract="true">
    <eSuperTypes href="../../org.eclipse.emf.ecore/model/Ecore.ecore#//ENamedElement"/>
    <eOperations name="getCaller">
      <eType xsi:type="ecore:EClass" href="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="getAction">
      <eType xsi:type="ecore:EClass" href="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MSEModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMSEs" upperBound="-1" eType="//MSE" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericMSE" eSuperTypes="//MSE">
    <eOperations name="getCaller">
      <eType xsi:type="ecore:EClass" href="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eOperations>
    <eOperations name="getAction">
      <eType xsi:type="ecore:EClass" href="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="callerReference">
      <eType xsi:type="ecore:EClass" href="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actionReference">
      <eType xsi:type="ecore:EClass" href="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mseoccurrence" eType="//MSEOccurrence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BigStep" abstract="true" eSuperTypes="//Step">
    <eTypeParameters name="StepSubtype">
      <eBounds eClassifier="//Step"/>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subSteps" upperBound="-1" containment="true">
      <eGenericType eTypeParameter="//BigStep/StepSubtype"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmallStep" abstract="true" eSuperTypes="//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequentialStep">
    <eTypeParameters name="StepSubtype">
      <eBounds eClassifier="//Step"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="//BigStep">
      <eTypeArguments eTypeParameter="//SequentialStep/StepSubtype"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelStep">
    <eTypeParameters name="StepSubtype">
      <eBounds eClassifier="//Step"/>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="//BigStep">
      <eTypeArguments eTypeParameter="//ParallelStep/StepSubtype"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericSequentialStep">
    <eGenericSuperTypes eClassifier="//SequentialStep">
      <eTypeArguments eClassifier="//Step"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericParallelStep">
    <eGenericSuperTypes eClassifier="//ParallelStep">
      <eTypeArguments eClassifier="//Step"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenericSmallStep" eSuperTypes="//SmallStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eTypeParameters name="StepSubType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootStep" lowerBound="1" containment="true">
      <eGenericType eTypeParameter="//Trace/StepSubType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="launchconfiguration" lowerBound="1" eType="//LaunchConfiguration" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LaunchConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="//LaunchConfigurationParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" defaultValueLiteral="">
      <eType xsi:type="ecore:EDataType" href="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LaunchConfigurationParameter" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
      <eType xsi:type="ecore:EDataType" href="../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LanguageNameParameter" eSuperTypes="//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelURIParameter" eSuperTypes="//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnimatorURIParameter" eSuperTypes="//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntryPointParameter" eSuperTypes="//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelRootParameter" eSuperTypes="//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitializationMethodParameter" eSuperTypes="//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitializationArgumentsParameter" eSuperTypes="//LaunchConfigurationParameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddonExtensionParameter" eSuperTypes="//LaunchConfigurationParameter"/>
</ecore:EPackage>
