<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="traceSystem" nsURI="traceSystem" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="TraceSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" upperBound="-1"
        eType="#//GlobalState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedBooleanVariables"
        ordered="false" upperBound="-1" eType="#//TracedBooleanVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedMergeNodes" ordered="false"
        upperBound="-1" eType="#//TracedMergeNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedExecutableNodes"
        ordered="false" upperBound="-1" eType="#//TracedExecutableNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedOpaqueActions" ordered="false"
        upperBound="-1" eType="#//TracedOpaqueAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedStringVariables"
        ordered="false" upperBound="-1" eType="#//TracedStringVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedControlNodes" ordered="false"
        upperBound="-1" eType="#//TracedControlNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedInputs" ordered="false"
        upperBound="-1" eType="#//TracedInput" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedTokens" ordered="false"
        upperBound="-1" eType="#//TracedToken" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedControlFlows" ordered="false"
        upperBound="-1" eType="#//TracedControlFlow" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedTraces" ordered="false"
        upperBound="-1" eType="#//TracedTrace" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedActivityNodes" ordered="false"
        upperBound="-1" eType="#//TracedActivityNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedForkNodes" ordered="false"
        upperBound="-1" eType="#//TracedForkNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedActions" ordered="false"
        upperBound="-1" eType="#//TracedAction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedControlTokens" ordered="false"
        upperBound="-1" eType="#//TracedControlToken" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedVariables" ordered="false"
        upperBound="-1" eType="#//TracedVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedJoinNodes" ordered="false"
        upperBound="-1" eType="#//TracedJoinNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedActivityFinalNodes"
        ordered="false" upperBound="-1" eType="#//TracedActivityFinalNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedActivityEdges" ordered="false"
        upperBound="-1" eType="#//TracedActivityEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedForkedTokens" ordered="false"
        upperBound="-1" eType="#//TracedForkedToken" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedOffers" ordered="false"
        upperBound="-1" eType="#//TracedOffer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedInitialNodes" ordered="false"
        upperBound="-1" eType="#//TracedInitialNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedIntegerVariables"
        ordered="false" upperBound="-1" eType="#//TracedIntegerVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedFinalNodes" ordered="false"
        upperBound="-1" eType="#//TracedFinalNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedDecisionNodes" ordered="false"
        upperBound="-1" eType="#//TracedDecisionNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedActivitys" ordered="false"
        upperBound="-1" eType="#//TracedActivity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedInputValues" ordered="false"
        upperBound="-1" eType="#//TracedInputValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_mainEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_mainEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_mainExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_mainExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_initializeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_initializeEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_initializeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_initializeExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_runEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_runEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_runExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_runExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_runNodesEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_runNodesEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_runNodesExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_runNodesExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_fireInitialNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_fireInitialNodeEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_fireInitialNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_fireInitialNodeExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_getEnabledNodesEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_getEnabledNodesEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_getEnabledNodesExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_getEnabledNodesExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_selectNextNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_selectNextNodeEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_selectNextNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_selectNextNodeExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_terminateEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_terminateEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_terminateExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_terminateExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_getInitialNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_getInitialNodeEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_getInitialNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_getInitialNodeExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_fireNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_fireNodeEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Activity_fireNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Activity_fireNodeExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_run_activityNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_run_activityNodeEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_run_activityNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_run_activityNodeExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_isRunningEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_isRunningEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_isRunningExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_isRunningExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_terminate_activityNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_terminate_activityNodeEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_terminate_activityNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_terminate_activityNodeExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_sendOffersEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_sendOffersEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_sendOffersExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_sendOffersExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_takeOfferedTokensEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_takeOfferedTokensEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_takeOfferedTokensExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_takeOfferedTokensExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_addTokensEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_addTokensEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_addTokensExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_addTokensExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_removeTokenEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_removeTokenEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_removeTokenExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_removeTokenExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_hasOffersEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_hasOffersEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_hasOffersExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_hasOffersExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_isReadyEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_isReadyEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityNode_isReadyExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityNode_isReadyExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityEdge_sendOfferEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityEdge_sendOfferEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityEdge_sendOfferExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityEdge_sendOfferExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityEdge_takeOfferedTokens_activityEdgeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityEdge_takeOfferedTokens_activityEdgeEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityEdge_takeOfferedTokens_activityEdgeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityEdge_takeOfferedTokens_activityEdgeExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityEdge_hasOfferEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityEdge_hasOfferEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityEdge_hasOfferExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityEdge_hasOfferExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControlNode_isReady_ControlNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ControlNode_isReady_ControlNodeEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControlNode_isReady_ControlNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ControlNode_isReady_ControlNodeExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControlNode_fire_controlNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ControlNode_fire_controlNodeEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControlNode_fire_controlNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ControlNode_fire_controlNodeExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Action_sendOffers_actionEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Action_sendOffers_actionEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Action_sendOffers_actionExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Action_sendOffers_actionExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Action_isReady_actionEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Action_isReady_actionEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Action_isReady_actionExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Action_isReady_actionExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Action_fire_actionEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Action_fire_actionEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Action_fire_actionExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Action_fire_actionExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OpaqueAction_doAction_opaqueActionEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//OpaqueAction_doAction_opaqueActionEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OpaqueAction_doAction_opaqueActionExitEventOccurrence_Trace"
        upperBound="-1" eType="#//OpaqueAction_doAction_opaqueActionExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InitialNode_isReady_InitialNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//InitialNode_isReady_InitialNodeEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InitialNode_isReady_InitialNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//InitialNode_isReady_InitialNodeExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InitialNode_fire_initialNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//InitialNode_fire_initialNodeEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InitialNode_fire_initialNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//InitialNode_fire_initialNodeExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityFinalNode_fire_activityFinalNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityFinalNode_fire_activityFinalNodeEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityFinalNode_fire_activityFinalNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ActivityFinalNode_fire_activityFinalNodeExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ForkNode_fire_forkNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ForkNode_fire_forkNodeEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ForkNode_fire_forkNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ForkNode_fire_forkNodeExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MergeNode_hasOffers_mergeNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//MergeNode_hasOffers_mergeNodeEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MergeNode_hasOffers_mergeNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//MergeNode_hasOffers_mergeNodeExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DecisionNode_fire_decisionNodeEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//DecisionNode_fire_decisionNodeEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DecisionNode_fire_decisionNodeExitEventOccurrence_Trace"
        upperBound="-1" eType="#//DecisionNode_fire_decisionNodeExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerVariable_setCurrentValue_integerVariableEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerVariable_setCurrentValue_integerVariableEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerVariable_setCurrentValue_integerVariableExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerVariable_setCurrentValue_integerVariableExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerVariable_getCurrentValueValue_integerVariableEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerVariable_getCurrentValueValue_integerVariableEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerVariable_getCurrentValueValue_integerVariableExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerVariable_getCurrentValueValue_integerVariableExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StringVariable_setCurrentValue_stringVariableEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//StringVariable_setCurrentValue_stringVariableEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StringVariable_setCurrentValue_stringVariableExitEventOccurrence_Trace"
        upperBound="-1" eType="#//StringVariable_setCurrentValue_stringVariableExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StringVariable_getCurrentValueValue_stringVariableEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//StringVariable_getCurrentValueValue_stringVariableEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StringVariable_getCurrentValueValue_stringVariableExitEventOccurrence_Trace"
        upperBound="-1" eType="#//StringVariable_getCurrentValueValue_stringVariableExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanVariable_setCurrentValue_boolenVariableEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanVariable_setCurrentValue_boolenVariableEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanVariable_setCurrentValue_boolenVariableExitEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanVariable_setCurrentValue_boolenVariableExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanVariable_getCurrentValueValue_booleanVariableEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanVariable_getCurrentValueValue_booleanVariableEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanVariable_getCurrentValueValue_booleanVariableExitEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanVariable_getCurrentValueValue_booleanVariableExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerExpression_getOperandCurrentValuesEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerExpression_getOperandCurrentValuesEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerExpression_getOperandCurrentValuesExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerExpression_getOperandCurrentValuesExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerCalculationExpression_execute_integerCalculationExpressionEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerCalculationExpression_execute_integerCalculationExpressionEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerCalculationExpression_execute_integerCalculationExpressionExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerCalculationExpression_execute_integerCalculationExpressionExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerCalculationExpression_evaluateADDEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerCalculationExpression_evaluateADDEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerCalculationExpression_evaluateADDExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerCalculationExpression_evaluateADDExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerCalculationExpression_evaluateSUBTRACTEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerCalculationExpression_evaluateSUBTRACTEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerCalculationExpression_evaluateSUBTRACTExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerCalculationExpression_evaluateSUBTRACTExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_execute_IntegerComparisionExpressionEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_execute_IntegerComparisionExpressionEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_execute_IntegerComparisionExpressionExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_execute_IntegerComparisionExpressionExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_evaluateSMALLEREntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_evaluateSMALLEREntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_evaluateSMALLERExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_evaluateSMALLERExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_evaluateSMALLER_EQUALSEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_evaluateSMALLER_EQUALSEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_evaluateSMALLER_EQUALSExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_evaluateSMALLER_EQUALSExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_evaluateEQUALSEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_evaluateEQUALSEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_evaluateEQUALSExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_evaluateEQUALSExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_evaluateGREATER_EQUALSEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_evaluateGREATER_EQUALSEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_evaluateGREATER_EQUALSExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_evaluateGREATER_EQUALSExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_evaluateGREATEREntryEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_evaluateGREATEREntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IntegerComparisonExpression_evaluateGREATERExitEventOccurrence_Trace"
        upperBound="-1" eType="#//IntegerComparisonExpression_evaluateGREATERExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanUnaryExpression_execute_booleanUnaryExpressionEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanUnaryExpression_execute_booleanUnaryExpressionEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanUnaryExpression_execute_booleanUnaryExpressionExitEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanUnaryExpression_execute_booleanUnaryExpressionExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanUnaryExpression_evaluateNOTEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanUnaryExpression_evaluateNOTEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanUnaryExpression_evaluateNOTExitEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanUnaryExpression_evaluateNOTExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanBinaryExpression_execute_booleanBinaryExpressionEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanBinaryExpression_execute_booleanBinaryExpressionEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanBinaryExpression_execute_booleanBinaryExpressionExitEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanBinaryExpression_execute_booleanBinaryExpressionExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanBinaryExpression_evaluateANDEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanBinaryExpression_evaluateANDEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanBinaryExpression_evaluateANDExitEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanBinaryExpression_evaluateANDExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanBinaryExpression_evaluateOREntryEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanBinaryExpression_evaluateOREntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanBinaryExpression_evaluateORExitEventOccurrence_Trace"
        upperBound="-1" eType="#//BooleanBinaryExpression_evaluateORExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Token_isWithdrawnEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Token_isWithdrawnEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Token_isWithdrawnExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Token_isWithdrawnExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Token_transferEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Token_transferEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Token_transferExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Token_transferExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Token_withdrawEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Token_withdrawEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Token_withdrawExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Token_withdrawExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ForkedToken_withdraw_forkedTokenEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//ForkedToken_withdraw_forkedTokenEntryEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ForkedToken_withdraw_forkedTokenExitEventOccurrence_Trace"
        upperBound="-1" eType="#//ForkedToken_withdraw_forkedTokenExitEventOccurrence"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Offer_hasTokensEntryEventOccurrence_Trace"
        upperBound="-1" eType="#//Offer_hasTokensEntryEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Offer_hasTokensExitEventOccurrence_Trace"
        upperBound="-1" eType="#//Offer_hasTokensExitEventOccurrence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pool_NamedElements" upperBound="-1"
        eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pool_IntegerComparisonExpressions"
        upperBound="-1" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerComparisonExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pool_BooleanBinaryExpressions"
        upperBound="-1" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//BooleanBinaryExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pool_IntegerExpressions"
        upperBound="-1" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pool_BooleanUnaryExpressions"
        upperBound="-1" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//BooleanUnaryExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pool_Values" upperBound="-1"
        eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pool_IntegerCalculationExpressions"
        upperBound="-1" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerCalculationExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventOccurrence" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateDuringWhichTriggered"
        lowerBound="1" eType="#//GlobalState" eOpposite="#//GlobalState/eventsTriggeredDuringState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GlobalState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventsTriggeredDuringState"
        upperBound="-1" eType="#//EventOccurrence" eOpposite="#//EventOccurrence/stateDuringWhichTriggered"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input_inputValues_States"
        ordered="false" upperBound="-1" eType="#//Input_inputValues_State" eOpposite="#//Input_inputValues_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="token_holder_States" ordered="false"
        upperBound="-1" eType="#//Token_holder_State" eOpposite="#//Token_holder_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace_executedNodes_States"
        ordered="false" upperBound="-1" eType="#//Trace_executedNodes_State" eOpposite="#//Trace_executedNodes_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityNode_running_States"
        ordered="false" upperBound="-1" eType="#//ActivityNode_running_State" eOpposite="#//ActivityNode_running_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityNode_heldTokens_States"
        ordered="false" upperBound="-1" eType="#//ActivityNode_heldTokens_State" eOpposite="#//ActivityNode_heldTokens_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable_currentValue_States"
        ordered="false" upperBound="-1" eType="#//Variable_currentValue_State" eOpposite="#//Variable_currentValue_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityEdge_offers_States"
        ordered="false" upperBound="-1" eType="#//ActivityEdge_offers_State" eOpposite="#//ActivityEdge_offers_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forkedToken_remainingOffersCount_States"
        ordered="false" upperBound="-1" eType="#//ForkedToken_remainingOffersCount_State"
        eOpposite="#//ForkedToken_remainingOffersCount_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forkedToken_baseToken_States"
        ordered="false" upperBound="-1" eType="#//ForkedToken_baseToken_State" eOpposite="#//ForkedToken_baseToken_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forkedToken_baseTokenIsWithdrawn_States"
        ordered="false" upperBound="-1" eType="#//ForkedToken_baseTokenIsWithdrawn_State"
        eOpposite="#//ForkedToken_baseTokenIsWithdrawn_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="offer_offeredTokens_States"
        ordered="false" upperBound="-1" eType="#//Offer_offeredTokens_State" eOpposite="#//Offer_offeredTokens_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity_trace_States"
        ordered="false" upperBound="-1" eType="#//Activity_trace_State" eOpposite="#//Activity_trace_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputValue_variable_States"
        ordered="false" upperBound="-1" eType="#//InputValue_variable_State" eOpposite="#//InputValue_variable_State/globalStates"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputValue_value_States"
        ordered="false" upperBound="-1" eType="#//InputValue_value_State" eOpposite="#//InputValue_value_State/globalStates"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedBooleanVariable" eSuperTypes="#//TracedVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//BooleanVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedMergeNode" eSuperTypes="#//TracedControlNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//MergeNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedExecutableNode" abstract="true"
      eSuperTypes="#//TracedActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="TracedOpaqueAction" eSuperTypes="#//TracedAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//OpaqueAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedStringVariable" eSuperTypes="#//TracedVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//StringVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedControlNode" abstract="true" eSuperTypes="#//TracedActivityNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="TracedInput">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputValuesTrace" upperBound="-1"
        eType="#//Input_inputValues_State" containment="true" eOpposite="#//Input_inputValues_State/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input_inputValues_State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputValues" upperBound="-1"
        eType="#//TracedInputValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedInput" eOpposite="#//TracedInput/inputValuesTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/input_inputValues_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedToken" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="holderTrace" upperBound="-1"
        eType="#//Token_holder_State" containment="true" eOpposite="#//Token_holder_State/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token_holder_State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="holder" lowerBound="1"
        eType="#//TracedActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedToken" eOpposite="#//TracedToken/holderTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/token_holder_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedControlFlow" eSuperTypes="#//TracedActivityEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//ControlFlow"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedTrace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executedNodesTrace" upperBound="-1"
        eType="#//Trace_executedNodes_State" containment="true" eOpposite="#//Trace_executedNodes_State/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trace_executedNodes_State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="executedNodes" upperBound="-1"
        eType="#//TracedActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedTrace" eOpposite="#//TracedTrace/executedNodesTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/trace_executedNodes_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedActivityNode" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="runningTrace" upperBound="-1"
        eType="#//ActivityNode_running_State" containment="true" eOpposite="#//ActivityNode_running_State/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heldTokensTrace" upperBound="-1"
        eType="#//ActivityNode_heldTokens_State" containment="true" eOpposite="#//ActivityNode_heldTokens_State/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_running_State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="running" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedActivityNode" eOpposite="#//TracedActivityNode/runningTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/activityNode_running_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_heldTokens_State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="heldTokens" upperBound="-1"
        eType="#//TracedToken" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedActivityNode" eOpposite="#//TracedActivityNode/heldTokensTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/activityNode_heldTokens_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedForkNode" eSuperTypes="#//TracedControlNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//ForkNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedAction" abstract="true" eSuperTypes="#//TracedExecutableNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="TracedControlToken" eSuperTypes="#//TracedToken"/>
  <eClassifiers xsi:type="ecore:EClass" name="TracedVariable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentValueTrace" upperBound="-1"
        eType="#//Variable_currentValue_State" containment="true" eOpposite="#//Variable_currentValue_State/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable_currentValue_State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentValue" lowerBound="1"
        eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//Value" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedVariable" eOpposite="#//TracedVariable/currentValueTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/variable_currentValue_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedJoinNode" eSuperTypes="#//TracedControlNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//JoinNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedActivityFinalNode" eSuperTypes="#//TracedFinalNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//ActivityFinalNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedActivityEdge" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="offersTrace" upperBound="-1"
        eType="#//ActivityEdge_offers_State" containment="true" eOpposite="#//ActivityEdge_offers_State/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge_offers_State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="offers" upperBound="-1"
        eType="#//TracedOffer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedActivityEdge" eOpposite="#//TracedActivityEdge/offersTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/activityEdge_offers_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedForkedToken" eSuperTypes="#//TracedToken">
    <eStructuralFeatures xsi:type="ecore:EReference" name="remainingOffersCountTrace"
        upperBound="-1" eType="#//ForkedToken_remainingOffersCount_State" containment="true"
        eOpposite="#//ForkedToken_remainingOffersCount_State/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseTokenTrace" upperBound="-1"
        eType="#//ForkedToken_baseToken_State" containment="true" eOpposite="#//ForkedToken_baseToken_State/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseTokenIsWithdrawnTrace"
        upperBound="-1" eType="#//ForkedToken_baseTokenIsWithdrawn_State" containment="true"
        eOpposite="#//ForkedToken_baseTokenIsWithdrawn_State/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkedToken_remainingOffersCount_State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remainingOffersCount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedForkedToken" eOpposite="#//TracedForkedToken/remainingOffersCountTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/forkedToken_remainingOffersCount_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkedToken_baseToken_State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseToken" lowerBound="1"
        eType="#//TracedToken"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedForkedToken" eOpposite="#//TracedForkedToken/baseTokenTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/forkedToken_baseToken_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkedToken_baseTokenIsWithdrawn_State">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseTokenIsWithdrawn" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedForkedToken" eOpposite="#//TracedForkedToken/baseTokenIsWithdrawnTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/forkedToken_baseTokenIsWithdrawn_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedOffer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="offeredTokensTrace" upperBound="-1"
        eType="#//Offer_offeredTokens_State" containment="true" eOpposite="#//Offer_offeredTokens_State/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Offer_offeredTokens_State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="offeredTokens" upperBound="-1"
        eType="#//TracedToken"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedOffer" eOpposite="#//TracedOffer/offeredTokensTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/offer_offeredTokens_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedInitialNode" eSuperTypes="#//TracedControlNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//InitialNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedIntegerVariable" eSuperTypes="#//TracedVariable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedFinalNode" abstract="true" eSuperTypes="#//TracedControlNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="TracedDecisionNode" eSuperTypes="#//TracedControlNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//DecisionNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedActivity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originalObject" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceTrace" upperBound="-1"
        eType="#//Activity_trace_State" containment="true" eOpposite="#//Activity_trace_State/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_trace_State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trace" lowerBound="1" eType="#//TracedTrace"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedActivity" eOpposite="#//TracedActivity/traceTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/activity_trace_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TracedInputValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableTrace" upperBound="-1"
        eType="#//InputValue_variable_State" containment="true" eOpposite="#//InputValue_variable_State/parent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueTrace" upperBound="-1"
        eType="#//InputValue_value_State" containment="true" eOpposite="#//InputValue_value_State/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputValue_variable_State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//TracedVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedInputValue" eOpposite="#//TracedInputValue/variableTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/inputValue_variable_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputValue_value_State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//Value"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//TracedInputValue" eOpposite="#//TracedInputValue/valueTrace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="globalStates" lowerBound="1"
        upperBound="-1" eType="#//GlobalState" eOpposite="#//GlobalState/inputValue_value_States"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_mainEntryEventOccurrence" eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputValuesParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_mainExitEventOccurrence" eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Activity_mainEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_initializeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputValuesParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_initializeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Activity_initializeEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_runEntryEventOccurrence" eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_runExitEventOccurrence" eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Activity_runEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_runNodesEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_runNodesExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Activity_runNodesEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_fireInitialNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_fireInitialNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Activity_fireInitialNodeEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_getEnabledNodesEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_getEnabledNodesExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Activity_getEnabledNodesEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enabledNodesReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_selectNextNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activityNodesParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_selectNextNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Activity_selectNextNodeEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedNodeReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_terminateEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_terminateExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Activity_terminateEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_getInitialNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_getInitialNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Activity_getInitialNodeEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialNodeReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_fireNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity_fireNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Activity_fireNodeEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_run_activityNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_run_activityNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityNode_run_activityNodeEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_isRunningEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_isRunningExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityNode_isRunningEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isRunningReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_terminate_activityNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_terminate_activityNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityNode_terminate_activityNodeEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_sendOffersEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokensParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_sendOffersExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityNode_sendOffersEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_takeOfferedTokensEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_takeOfferedTokensExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityNode_takeOfferedTokensEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokensReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_addTokensEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokensParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_addTokensExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityNode_addTokensEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_removeTokenEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokenParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_removeTokenExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityNode_removeTokenEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_hasOffersEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_hasOffersExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityNode_hasOffersEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_isReadyEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode_isReadyExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityNode_isReadyEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isReadyReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge_sendOfferEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokensParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge_sendOfferExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityEdge_sendOfferEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge_takeOfferedTokens_activityEdgeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge_takeOfferedTokens_activityEdgeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityEdge_takeOfferedTokens_activityEdgeEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokensReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge_hasOfferEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge_hasOfferExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityEdge_hasOfferEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasOfferReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlNode_isReady_ControlNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedControlNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlNode_isReady_ControlNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ControlNode_isReady_ControlNodeEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isReadyReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlNode_fire_controlNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedControlNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokensParam" eType="#//TracedToken"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlNode_fire_controlNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ControlNode_fire_controlNodeEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action_sendOffers_actionEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action_sendOffers_actionExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Action_sendOffers_actionEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action_isReady_actionEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action_isReady_actionExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Action_isReady_actionEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isReadyReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action_fire_actionEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedAction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokensParam" eType="#//TracedToken"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action_fire_actionExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Action_fire_actionEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpaqueAction_doAction_opaqueActionEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedOpaqueAction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OpaqueAction_doAction_opaqueActionExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//OpaqueAction_doAction_opaqueActionEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode_isReady_InitialNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedInitialNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode_isReady_InitialNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//InitialNode_isReady_InitialNodeEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isReadyReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode_fire_initialNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedInitialNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokensParam" eType="#//TracedToken"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InitialNode_fire_initialNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//InitialNode_fire_initialNodeEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityFinalNode_fire_activityFinalNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedActivityFinalNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokensParam" eType="#//TracedToken"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityFinalNode_fire_activityFinalNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ActivityFinalNode_fire_activityFinalNodeEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkNode_fire_forkNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedForkNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokensParam" eType="#//TracedToken"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkNode_fire_forkNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ForkNode_fire_forkNodeEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergeNode_hasOffers_mergeNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedMergeNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergeNode_hasOffers_mergeNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//MergeNode_hasOffers_mergeNodeEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionNode_fire_decisionNodeEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedDecisionNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tokensParam" eType="#//TracedToken"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionNode_fire_decisionNodeExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//DecisionNode_fire_decisionNodeEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerVariable_setCurrentValue_integerVariableEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedIntegerVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerVariable_setCurrentValue_integerVariableExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerVariable_setCurrentValue_integerVariableEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerVariable_getCurrentValueValue_integerVariableEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedIntegerVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerVariable_getCurrentValueValue_integerVariableExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerVariable_getCurrentValueValue_integerVariableEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringVariable_setCurrentValue_stringVariableEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedStringVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringVariable_setCurrentValue_stringVariableExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//StringVariable_setCurrentValue_stringVariableEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringVariable_getCurrentValueValue_stringVariableEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedStringVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringVariable_getCurrentValueValue_stringVariableExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//StringVariable_getCurrentValueValue_stringVariableEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanVariable_setCurrentValue_boolenVariableEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedBooleanVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanVariable_setCurrentValue_boolenVariableExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//BooleanVariable_setCurrentValue_boolenVariableEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanVariable_getCurrentValueValue_booleanVariableEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedBooleanVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanVariable_getCurrentValueValue_booleanVariableExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//BooleanVariable_getCurrentValueValue_booleanVariableEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerExpression_getOperandCurrentValuesEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerExpression_getOperandCurrentValuesExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerExpression_getOperandCurrentValuesEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand1ValueReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand2ValueReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerCalculationExpression_execute_integerCalculationExpressionEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerCalculationExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerCalculationExpression_execute_integerCalculationExpressionExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerCalculationExpression_execute_integerCalculationExpressionEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerCalculationExpression_evaluateADDEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerCalculationExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerCalculationExpression_evaluateADDExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerCalculationExpression_evaluateADDEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerCalculationExpression_evaluateSUBTRACTEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerCalculationExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerCalculationExpression_evaluateSUBTRACTExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerCalculationExpression_evaluateSUBTRACTEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_execute_IntegerComparisionExpressionEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerComparisonExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_execute_IntegerComparisionExpressionExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerComparisonExpression_execute_IntegerComparisionExpressionEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_evaluateSMALLEREntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerComparisonExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_evaluateSMALLERExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerComparisonExpression_evaluateSMALLEREntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_evaluateSMALLER_EQUALSEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerComparisonExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_evaluateSMALLER_EQUALSExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerComparisonExpression_evaluateSMALLER_EQUALSEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_evaluateEQUALSEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerComparisonExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_evaluateEQUALSExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerComparisonExpression_evaluateEQUALSEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_evaluateGREATER_EQUALSEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerComparisonExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_evaluateGREATER_EQUALSExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerComparisonExpression_evaluateGREATER_EQUALSEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_evaluateGREATEREntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//IntegerComparisonExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerComparisonExpression_evaluateGREATERExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//IntegerComparisonExpression_evaluateGREATEREntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanUnaryExpression_execute_booleanUnaryExpressionEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//BooleanUnaryExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanUnaryExpression_execute_booleanUnaryExpressionExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//BooleanUnaryExpression_execute_booleanUnaryExpressionEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanUnaryExpression_evaluateNOTEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//BooleanUnaryExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanUnaryExpression_evaluateNOTExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//BooleanUnaryExpression_evaluateNOTEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanBinaryExpression_execute_booleanBinaryExpressionEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//BooleanBinaryExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanBinaryExpression_execute_booleanBinaryExpressionExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//BooleanBinaryExpression_execute_booleanBinaryExpressionEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanBinaryExpression_evaluateANDEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//BooleanBinaryExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanBinaryExpression_evaluateANDExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//BooleanBinaryExpression_evaluateANDEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanBinaryExpression_evaluateOREntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//BooleanBinaryExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanBinaryExpression_evaluateORExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//BooleanBinaryExpression_evaluateOREntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token_isWithdrawnEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedToken"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token_isWithdrawnExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Token_isWithdrawnEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isWithdrawnReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token_transferEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedToken"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="holderParam" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token_transferExitEventOccurrence" eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Token_transferEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transferredTokenReturn"
        eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token_withdrawEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedToken"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token_withdrawExitEventOccurrence" eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Token_withdrawEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkedToken_withdraw_forkedTokenEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedForkedToken"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForkedToken_withdraw_forkedTokenExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//ForkedToken_withdraw_forkedTokenEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Offer_hasTokensEntryEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="#//TracedOffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Offer_hasTokensExitEventOccurrence"
      eSuperTypes="#//EventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Offer_hasTokensEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasTokensReturn" eType="ecore:EClass ../model_inputs/activitydiagram.ecore#//NamedElement"/>
  </eClassifiers>
</ecore:EPackage>
