<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="base" nsURI="http://base/1.0" nsPrefix="base">
  <eClassifiers xsi:type="ecore:EClass" name="Trace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statesTrace" upperBound="-1"
        eType="#//State" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" lowerBound="1"
        eType="#//Events/Events" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracedObjects" lowerBound="1"
        eType="#//Traced/TracedObjects" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="followingEvent" eType="#//Events/Event"
        eOpposite="#//Events/Event/precedingState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="macroEvents" eType="#//Events/MacroEvent"
        eOpposite="#//Events/MacroEvent/precedingState"/>
  </eClassifiers>
  <eSubpackages name="Events" nsURI="http://events/1.0" nsPrefix="events">
    <eClassifiers xsi:type="ecore:EClass" name="Event" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="precedingState" lowerBound="1"
          eType="#//State" eOpposite="#//State/followingEvent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Events"/>
    <eClassifiers xsi:type="ecore:EClass" name="MacroEvent" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="precedingState" lowerBound="1"
          eType="#//State" eOpposite="#//State/macroEvents"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="followingState" eType="#//State"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="Values" nsURI="http://states/1.0" nsPrefix="states"/>
  <eSubpackages name="Traced" nsURI="http://tracedclasses/1.0" nsPrefix="tracedclasses">
    <eClassifiers xsi:type="ecore:EClass" name="TracedObjects"/>
  </eSubpackages>
</ecore:EPackage>
