<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eventsMM" nsURI="http://eventsMM/1.0" nsPrefix="eventsMM">
  <eClassifiers xsi:type="ecore:EClass" name="Net_mainEntryEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/petrinet.ecore#//Net"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Net_mainExitEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Net_mainEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Net_runEntryEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/petrinet.ecore#//Net"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Net_runExitEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Net_runEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place_addTokenEntryEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/petrinet.ecore#//Place"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place_addTokenExitEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Place_addTokenEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place_removeTokenEntryEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/petrinet.ecore#//Place"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place_removeTokenExitEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Place_removeTokenEntryEventOccurrence"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition_isEnabledEntryEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/petrinet.ecore#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition_isEnabledExitEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Transition_isEnabledEntryEventOccurrence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnReturn" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition_fireEntryEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="thisParam" eType="ecore:EClass ../model_inputs/petrinet.ecore#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition_fireExitEventOccurrence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingEntryEvent"
        eType="#//Transition_fireEntryEventOccurrence"/>
  </eClassifiers>
</ecore:EPackage>
